# -*- coding: utf-8 -*-
"""Customer Churn EDA & Retention Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Qgrse3lbuHOrzrhSQp5tzdoXdJsOsMQ

# Customer churn EDA & Retention Segmentation
##To identify why customers leave a telecom company, which customer segments are at highest risk, and how much revenue is at stake — then translate those findings into specific, prioritised business actions the retention team can execute immediately.

#Objective:
##Clean and explore 7,043 customer records using Pandas. Build 6 visualisations (Seaborn + Matplotlib) that surface churn patterns by contract, tenure, charges, internet service, and payment method. Produce a correlation chart ranking the strongest churn drivers

## Phase 1:Data Quality and Pre-processing.
"""

# Import our all library first.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data.
df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")

# Now we do some analysis to understa our data .

# Fisrt we check the shape of our data set.
print(f"The shape of our data is :{df.shape}")

# Check the columns.
print(f"\nThe Columns our data have : {df.columns}")

# Check for the structue and the duplicated rows in the data.
print("Dataset Shape:", df.shape) # (7043, 21)
print("Duplicate Rows:", df.duplicated().sum())
print(f"We have total {df.duplicated().sum()} Duplicated Rows in Data.")

# Now check the data types of each column.
print(f"\n<-------------- The data types of each column------------->")
print(df.dtypes)

# small information about our data.
print(f"\n The small summary of our data")
df.info()

# First 10 rows of our dataset.
print(f"\n The fisrt 10 rowsof our data set")
(df.head(10))

# Last 10 rows of our dataset.
print(f"\n The last 10 rows of our data set")
(df.tail(10))

# TotalCharges contains empty strings (" ") for 11 new customers.
# pd.to_numeric with errors='coerce' forces these to NaN.
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print(f"Corrupted TotalCharges entries found: {df['TotalCharges'].isnull().sum()}")

# Fill nulls with 0 (since tenure is 0, they owe $0)
df['TotalCharges'] = df['TotalCharges'].fillna(0)

# Convert 'Yes'/'No' to 1/0 for mathematical aggregation
df['Churn_num'] = (df['Churn'] == 'Yes').astype(int)

# Now Lets have a Look of our final data.
df

"""## Phase 2: Business Analysis(EDA)."""

# What is the baseline churn rate?
churn_rate = df['Churn_num'].mean()*100.00
print(f"Baseline churn rate: {churn_rate:.2f}%")

# How does contract type dictate customer loyalty?
print('\nContract type Dictate  customer loyalty')
print((df.groupby('Contract')['Churn_num'].mean()* 100.00).round(1))

# Demoghraphic -senior churn rate.
print("\n Churn by Senior Citizen (%):")
print((df.groupby('SeniorCitizen')['Churn_num'].mean() * 100).round(1))

# Does family status anchor customers?
print("Dose the Family stats Anchor Customer.")
print((df.groupby('Partner')['Churn_num'].mean()*100.00).round(1))
print("\n   Churn by Dependents (%):")
print((df.groupby('Dependents')['Churn_num'].mean() * 100).round(1))

# At what lifecycle stage do we lose them?
print("At what Life Cycle stage we lose the Customer")
print((df.groupby('Churn_num')['tenure'].mean().round(1)))

# Which core product is failing?
print("Churn by Internet Service(%)")
print((df.groupby('InternetService')['Churn_num'].mean()*100.00).round(1))

# Create a filtered dataframe for Fiber Optic customers (our problem segment)
fiber = df[df['InternetService'] == 'Fiber optic']

# Product - Tech Support (Fiber Optic only)
print("\n7. Fiber Optic Churn - Tech Support vs No Support (%):")
print((fiber.groupby('TechSupport')['Churn_num'].mean() * 100).round(1))

# Do add-on services save high-risk Fiber customers?
print("Add-on Service Churn Rate(%).")
print((df.groupby('TechSupport')['Churn_num'].mean()* 100.00).round(1))

# Product - Tech Support (Fiber Optic only)
print("\n Fiber Optic Churn - Tech Support vs No Support (%):")
print((fiber.groupby('TechSupport')['Churn_num'].mean() * 100).round(1))

# Does paperless billing correlate with churn?
print("\n9. Churn by Paperless Billing (%):")
print((df.groupby('PaperlessBilling')['Churn_num'].mean() * 100).round(1))

# Are we pricing them out?
print("\n10. Average Monthly Charges by Churn Status ($):")
print(df.groupby('Churn')['MonthlyCharges'].mean().round(2))

# Do multiple phone lines increase stickiness?
print("\n11. Churn by Multiple Lines (%):")
print((df.groupby('MultipleLines')['Churn_num'].mean() * 100).round(1))

# Does Device Protection matter?
print("\n12. Fiber Optic Churn - Device Protection vs No Protection (%):")
print((fiber.groupby('DeviceProtection')['Churn_num'].mean() * 100).round(1))



"""# Phase 3 :Visulization

## 1. Churn Rate by Contract Type.
"""

# Create a tenure band for lifecycle analysis
df['tenure_band'] = pd.cut(
    df['tenure'],
    bins=[0, 12, 24, 48, 72],
    labels=['0-12m', '13-24m', '25-48m', '49-72m']
)

# Apply global styling
sns.set_theme(style="whitegrid")

# Set the figure Size.
plt.figure(figsize=(8, 6))
contract_churn = (df.groupby('Contract')['Churn_num'].mean()* 100.00)

# Plot the bar Graph to see the Curstomer Churn By the Contract Type.
contract_churn.plot(kind='bar', color=['#ff5f5f', '#f5a623', '#2ecc88'])

plt.title("Churn Rate By Contact Type", fontweight='bold', fontsize=14)
plt.ylabel('Churn Rate (%)', fontsize=12)
plt.xlabel('Contract', fontsize=12)
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
plt.savefig('1_contract_churn.png', dpi=150)
plt.close()

"""## 2. Churn Rate By Tenure Band."""

# Set the Figure Size.
plt.figure(figsize=(8, 6))
tenure_churn = (df.groupby('tenure_band', observed='True')['Churn_num'].mean()*100.00)

# Plot the line Chart.
tenure_churn.plot(kind='line', marker='o', linewidth=2.5, markersize=8)

plt.title('Churn Rate by Customer Tenure', fontweight='bold', fontsize=14)
plt.ylabel('Churn Rate (%)', fontsize=12)
plt.xlabel('Tenure Band', fontsize=12)
plt.tight_layout()
plt.show()
plt.savefig('2_tenure_churn.png', dpi=150)
plt.close()

"""## 3. Churn By Monthly Charges"""

# Set the Figure Size.
plt.figure(figsize=(8, 5))
df[df['Churn']=='No']['MonthlyCharges'].hist(bins=30, alpha=0.6, color='#2ecc88', label='Retained')
df[df['Churn']=='Yes']['MonthlyCharges'].hist(bins=30, alpha=0.8, color='#ff5f5f', label='Churned')

plt.title('Monthly Charges: Retained vs Churned', fontweight='bold', fontsize=14)
plt.xlabel('Monthly Charges ($)', fontsize=12)
plt.ylabel('Number of Customers', fontsize=12)
plt.legend(loc='upper right')
plt.tight_layout()
plt.show()
plt.savefig('3_monthly_charges.png', dpi=150)
plt.close()

"""## 4.Churn By Internet Service"""

# Set the figuren Size.
plt.figure(figsize=(8, 5))
internet_churn = (df.groupby('InternetService')['Churn_num'].mean() * 100)
internet_churn.plot(kind='bar', color=['#2ecc88', '#ff5f5f', '#4f8eff'])

plt.title('Churn by Internet Service', fontweight='bold', fontsize=14)
plt.ylabel('Churn Rate (%)', fontsize=12)
plt.xlabel('Internet Service', fontsize=12)
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
plt.savefig('4_internet_churn.png', dpi=150)
plt.close()

"""## 5. Customer Churn By Payment Type."""

# Set the Figure Size.
plt.figure(figsize=(8, 5))
pay_churn = (df.groupby('PaymentMethod')['Churn_num'].mean() * 100).sort_values()
pay_churn.plot(kind='barh', color='#26d9c7')

plt.title('Churn Rate by Payment Method', fontweight='bold', fontsize=14)
plt.xlabel('Churn Rate (%)', fontsize=12)
plt.ylabel('') # Clear y-label for cleaner look
plt.tight_layout()
plt.show()
plt.savefig('5_payment_churn.png', dpi=150)
plt.close()

"""## 6. Heatmap For Top Correlated Drivers."""

# Set the figure size.
plt.figure(figsize=(8, 6))

# One-hot encode categorical variables, drop targets
df_enc = pd.get_dummies(df.drop(['customerID', 'Churn', 'tenure_band'], axis=1))

# Calculate Pearson correlation
corr = df_enc.corr()['Churn_num'].sort_values().drop('Churn_num')

# Filter for the strongest signals (correlation > 0.15 or < -0.15)
top_corr = corr[abs(corr) > 0.15]

# Apply color mapping
colors = ['#ff5f5f' if v > 0 else '#2ecc88' for v in top_corr]
top_corr.plot(kind='barh', color=colors)

plt.title('Top Correlated Features (Green=Retain, Red=Churn)', fontweight='bold', fontsize=14)
plt.xlabel('Pearson Correlation Coefficient', fontsize=12)
plt.tight_layout()
plt.show()
plt.savefig('6_correlations.png', dpi=150)
plt.close()

# Save the Cleaned Csv For the Analysis in Sql DataBase.
df.to_csv('Customer_churn_cleaned.csv', index=False)

"""# 🎯 Customer Churn EDA & Retention Segmentation: Insights & Conclusions

## 📌 Phase 1: Data Quality & Pre-processing
* **Data Structure:** Analyzed original dataset consisting of 7,043 rows and 21 columns.
* **Data Integrity:** Verified structural integrity by confirming the complete absence of duplicated rows.
* **Missing Values Handled:** Identified 11 corrupted `TotalCharges` entries containing empty strings; coerced these to null values and filled them with `$0`, as they represent new customers with `0` tenure.
* **Feature Engineering:**
  * Engineered a binary `Churn_num` target variable (converting 'Yes'/'No' to `1`/`0`) to enable mathematical aggregations.
  * Engineered a `tenure_band` categorical feature, binning continuous customer tenure into distinct lifecycle stages (`0-12m`, `13-24m`, `25-48m`, and `49-72m`).

## 📊 Phase 2: Exploratory Data Analysis (EDA) Insights
* **Contract Loyalty:** Month-to-month contracts are the single most powerful driver of customer attrition.
* **Demographic Risk:** Senior citizens churn at a significantly higher rate, while customers with partners or dependents exhibit strong retention (family status acts as an account anchor).
* **Lifecycle Attrition:** The primary "danger zone" for customer churn occurs within the first 12 months, after which loyalty sharply stabilizes.
* **Product Vulnerability:** Fiber Optic internet has the highest churn rate among core services, indicating a value-perception issue despite being the premium product.
* **Add-On Effectiveness:** Within the high-risk Fiber Optic segment, supplementary services—specifically **Tech Support** and **Device Protection**—dramatically reduce churn probability.
* **Financial Friction:** Higher average monthly charges, paperless billing, and electronic check payments all strongly correlate with elevated churn rates.

## 🎯 Phase 3: Conclusions & Feature Correlation
* **Statistical Preparation:** Performed one-hot encoding on categorical variables and dropped irrelevant identifiers (`customerID`) to isolate behavioral signals.
* **Correlation Analysis:** Calculated Pearson correlation coefficients against the `Churn_num` target to simultaneously rank all retention and attrition variables.
* **Key Drivers Identified:** Filtered for the strongest statistical signals (`|r| > 0.15`):
  * **Top Churn Drivers (Red):** Month-to-month contracts, Fiber optic service, Electronic check payments, and lack of Tech Support.
  * **Top Retention Drivers (Green):** Two-year contracts, longer tenure, and bundled add-on services.
* **Deployment Readiness:** Exported the fully transformed and cleaned dataset (`Customer_churn_cleaned.csv`) for advanced SQL database analysis and targeted retention strategy execution.
"""